server:
  servlet:
    context-path: /api

vichaar:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3000000


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
#    username: root
#    password: ubuntu@43
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#    show-sql: true

